language: node_js
node_js:
  - lts/*

install:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - sudo ./aws/install
  - rm -rf awscliv2.zip ./aws
  - yarn --frozen-lockfile

script:
  - yarn generate

deploy:
  provider: script
  skip_cleanup: true
  script: yarn deploy
  on:
    branch: master
